# display this help
default:
  just --list

# install nodejs dependencies locally
install-deps:
  npm install -g npm@8.7.0
  npm ci

# run tests locally
#test:
#  npm test

# build locally
build:
  npm run build

# build the api-server docker image
build-image:
  docker-compose build api-server

# publish the api-server docker image to docker.io
publish-image:
  docker login
  docker-compose push api-server

# start a local docker-based environment vis docker-compose
start: build-image
  docker-compose start 

# stop the local docker-based environment
stop: 
  docker-compose stop

# populate local db - requires host networking, different db params.  require a
# create the initial database schema by invoking ./docker-scripts/migrate.sh conn_string 
populate-db conn_string: 
  echo {{conn_string}}
#  docker-compose run api-server ./docker-scripts/migrate.sh
