name: build devcontainer image                                                                                                

on:
  push:
  workflow_dispatch:  # manual execution through Github UI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/infinite-industries/infinite-devcontainer
          cacheFrom: ghcr.io/infinite-industries/infinite-devcontainer
          push: always
          configFile: ./.devcontainer-prebuild/devcontainer.json
