name: Get Staging VM Status

on:
  workflow_dispatch:  # manual trigger only

jobs:
  get-staging-status:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: bin/azure
    steps:
      - name: checkout branch
        uses: actions/checkout@v7
      - name: get staging VM status
        env:
          AZURE_START_STOP_CLIENT_SECRET: ${{ secrets.AZURE_START_STOP_CLIENT_SECRET }}
        run: ./get-staging-status.sh
