name: Nest API Server Tests

on:
  pull_request:
    branches:
      - development
      - master
    paths:
      - 'api-server-nest/**'
  push:
    branches:
      - development
      - master
    paths:
      - 'api-server-nest/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.19'
      - name: Check Node version
        run: node --version
      - name: Install API Server Dependencies
        run: npm ci
        working-directory: './api-server-nest'
      - name: Run Tests
        run: npm run test:e2e
        working-directory: './api-server-nest'
        env:
          PORT: 3003
