on:
  pull_request:
    branches:
      - development
      - master
  workflow_dispatch:
    environment: docker-publication
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  log-the-inputs:
    environment: docker-publication
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Running Jerb"
          echo "Log level: $LEVEL"
          echo "Environment: $ENVIRONMENT"
          echo "Tell me your secrect: $TEST_SECRET"
          ehco "grr: $TEST_SECRET_2"
          echo "$(ls -l)"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}
