name: Stop Staging VM

on:
  workflow_dispatch:  # manual trigger only

jobs:
  stop-staging:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: bin/azure
    steps:
      - name: checkout branch
        uses: actions/checkout@v7
      - name: stop staging VM
        env:
          AZURE_START_STOP_CLIENT_SECRET: ${{ secrets.AZURE_START_STOP_CLIENT_SECRET }}
        run: ./stop-staging.sh
