name: Widget Tests

on:
  pull_request:
    branches:
      - development
      - master
    paths:
      - 'widget/**'
      - '.github/workflows/widget-tests.yml'
  push:
    branches:
      - development
      - master
    paths:
      - 'widget/**'
      - '.github/workflows/widget-tests.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Check Node version
        run: node --version
      - name: Install Widget Dependencies
        run: npm ci
        working-directory: './widget'
      - name: Run Unit Tests
        run: npm run test
        working-directory: './widget'
